### ISSUE TITLE
Make expectations mumukit-inspection compatible

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-xgobstones-runner#64]
@flbulgarelli said:

> The main difference between a gobstones-spec expectation a mumukit-inspection expectation, is that binding parameter is missing in gobstones-spec's expectations.
> 
> We should include it.

**Comment by flbulgarelli** [comment]
No further development will be done in this runner - except for bugfixing. New gobstones features will be addressed here: https://github.com/mumuki/mumuki-gobstones-runner.
